language: python
python:
    - "2.7"
install:
    - pip install -e . --use-mirrors
    - pip install coverage coveralls --use-mirrors
script:
    - coverage run `which nosetests` --nocapture
    - coverage report -m
after_success:
    - coveralls
